version: '2'
services:
  mongodb:
    build: ./mongodb
    ports:
     - "${mongodb_port}:${mongodb_port}"
    volumes:
     - ${data_dir}/mongodb:/data/db
     - ${logs_dir}/mongodb:/data/logs
  zookeeper:
    build: ./zookeeper
    ports:
     - "${zookeeper_port}:${zookeeper_port}"
    volumes:
     - ${data_dir}/zookeeper:/data/db
     - ${logs_dir}/zookeeper:/data/logs
