# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "'Story Line 2' Project's Site"
url: "https://fedor-malyshkin.github.io/story_line2_build/" # the base hostname & protocol for your site, e.g. http://example.com
social:
  name: Fedor Malyshkin
  links:
    - https://www.linkedin.com/in/fedor-malyshkin/
    - https://habrahabr.ru/users/fedor_malyshkin/
    - https://moikrug.ru/fedor-malyshkin
    - https://github.com/fedor-malyshkin
lang: en_US

# Contact data
github_link: https://github.com/fedor-malyshkin
linkedin_link: https://linkedin.com/in/fedor-malyshkin/
habrahabr_link: https://habrahabr.ru/users/fedor_malyshkin/
moikrug_link: https://moikrug.ru/fedor-malyshkin
telegram_link: https://t.me/fedor_malyshkin
telegram_user: "@fedor_malyshkin"
contact_email: fedor.malyshkin@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style: compressed

# theme: minima
# End

# Gem settings
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - SITECHANGELOG.md
# End

# Date format settings
date_format: "%b %-d, %Y"
# End

# Site permalink settings
permalink: /:title/
# End
